### ISSUE TITLE
One day delay between repo and dashboard

### ISSUE THREAD

**Issue by vi-enne** [ministero-salute/it-dgc-opendata#12]
# Issue content

It appears to exist a one day delay between the data uploaded in this repository and the [official dashboard](https://www.dgc.gov.it/spa/dashboard/).

Here's the last update for the file [dgc-issued.csv](https://github.com/ministero-salute/it-dgc-opendata/blob/268eed7cae596a99a634542dd0a4a53b33eb51b9/data/dgc-issued.csv): done during the night between 2021-10-31 and 2021-11-01, it reports data about 2021-10-30 instead of 2021-10-31.

![image](https://user-images.githubusercontent.com/44818674/139681625-87a31f57-1cfa-4fb2-a575-873efb78bdfa.png)

Conversely, the dashboard reports data up to 2021-10-31
![image](https://user-images.githubusercontent.com/44818674/139682144-89675da6-f142-4cfd-9c55-9833f86bb6ad.png)

Thanks for looking into the issue.

Vittorio

**Comment by sebaker88** [comment]
Solved
