### ISSUE TITLE
Data on green pass are not updated

### ISSUE THREAD

**Issue by sapomnia** [ministero-salute/it-dgc-opendata#18]
# Issue content
Repository containing data on green passes issued has not been updated since January 27h. Yet, on your website data are up to date. Any chance this can be fixed?

**Comment by dennisangemi** [comment]
https://github.com/ministero-salute/it-dgc-opendata/commit/a2ba5581437789754189c6da90c86640efd890ce it's ok, isn't it? Thx doc team ;)

**Comment by sapomnia** [comment]
It's been fixed. Thanks
